# Generated by Django 5.1.6 on 2025-03-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_quantity_gt_0_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='quantity_gt_0',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='cart_item_quantity',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('cart_item_quantity__gt', 0)), name='cart_item_quantity_gt_0'),
        ),
    ]
