# Generated by Django 5.1.6 on 2025-03-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='user_id',
            new_name='user',
        ),
    ]
