# Generated by Django 5.1.6 on 2025-03-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quick_overview',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
